scuelo/urls.py
from django.urls import path
from . import views
from .views import (
    StudentListView, StudentCreateView, SchoolManagementView, SchoolCreateView,
    SchoolUpdateView, SchoolDeleteView, SchoolDetailView, ClasseCreateView,
    ClasseDetailView, ClasseUpdateView, ClasseDeleteView
     , UniformPaymentListView, print_receipt  
      , login_view 
    
)

urlpatterns = [
    path('', views.home, name='home'),
    path('class/<int:pk>/', views.class_detail, name='class_detail'),


    path('login/', login_view, name='login'),

    path('update_paiement/<int:pk>/', views.update_paiement, name='update_paiement'),
    path('add_paiement/<int:pk>/', views.add_payment, name='add_paiement'),

    path('student_update/<int:pk>/', views.student_update, name='student_update'),  # Add this line
    path('logout/', views.logout_view, name='logout'),



    path('uniform_payments/', UniformPaymentListView.as_view(), name='uniform_payments'),


    path('offsite_students/', views.offsite_students, name='offsite_students'),
    path('directly_managed_students/', StudentListView.as_view(), name='directly_managed_students'),
    path('new_student/', StudentCreateView.as_view(), name='new_student'),
    path('change_school/<int:pk>/', views.change_school, name='change_school'),

    path('class_upgrade/<int:pk>/', views.class_upgrade, name='class_upgrade'),


  

    path('school_management/', SchoolManagementView.as_view(), name='school_management'),
    path('schools/create/', SchoolCreateView.as_view(), name='school_create'),
    path('schools/update/<int:pk>/', SchoolUpdateView.as_view(), name='school_update'),
    path('schools/delete/<int:pk>/', SchoolDeleteView.as_view(), name='school_delete'),
    path('schools/detail/<int:pk>/', SchoolDetailView.as_view(), name='school_detail'),

    path('classes/create/<int:pk>/', ClasseCreateView.as_view(), name='classe_create'),
    path('classes/detail/<int:pk>/', ClasseDetailView.as_view(), name='classe_detail'),
    path('classes/update/<int:pk>/', ClasseUpdateView.as_view(), name='classe_update'),
    path('classes/delete/<int:pk>/', ClasseDeleteView.as_view(), name='classe_delete'),
    path('load_classes/', views.load_classes, name='load_classes'),
    # Other URLs
 
 path('class/<int:pk>/manage-tarifs/', views.manage_tarifs, name='manage_tarifs'),
    path('class/<int:pk>/add-tarif/', views.add_tarif, name='add_tarif'),
    path('tarif/<int:pk>/edit/', views.update_tarif, name='update_tarif'),
    path('tarif/<int:pk>/delete/', views.delete_tarif, name='delete_tarif'),
    
 
     path('cash/flow_report/', views.cash_flow_report, name='cash_flow_report'),
     path('mouvements/', views.mouvement_list, name='mouvement_list'),
    path('mouvements/add/', views.add_mouvement, name='add_mouvement'),
    path('mouvements/update/<int:pk>/', views.update_mouvement, name='update_mouvement'),
    path('mouvements/delete/<int:pk>/', views.delete_mouvement, name='delete_mouvement'),
    #path('cash/accounting_export/', views.cash_accounting_export, name='cash_accounting_export'),
    path('student/<int:pk>/', views.student_detail, name='student_detail'),
  
    path('receipt/print/<int:mouvement_id>/', print_receipt, name='print_receipt'),
 path('late_payment_report/', views.late_payment_report, name='late_payment_report'),
    path('class/<int:pk>/manage-tarifs/', views.manage_tarifs, name='manage_tarifs'),
   # path('class/<int:pk>/add-tarif/', TarifCreateView.as_view(), name='add_tarif'),
   # path('tarif/<int:pk>/edit/', TarifUpdateView.as_view(), name='edit_tarif'),
   # path('tarif/<int:pk>/delete/', TarifDeleteView.as_view(), name='delete_tarif'),
    #path('tarif/<int:pk>/delete/', TarifDeleteView.as_view(), name='tarif_delete'),
     path('accounting_c_sco_report/', views.accounting_c_sco_report, name='accounting_c_sco_report'),
   path('accounting_c_sco_report/<str:period>/', views.accounting_c_sco_report, name='accounting_c_sco_report_period'),

    # Accounting Report - Bi-Monthly
    path('c_sco/accounting/bi_monthly/', views.accounting_c_sco_report, {'period': 'bi_monthly'}, name='accounting_c_sco_report_bi_monthly'),
]

sig/urls.py
from django.contrib import admin
from    . import settings
from django.urls import include, path
from scuelo.admin import sics_site
from django.conf.urls.static import static
from  scuelo.views  import  login_view

urlpatterns = [
    path('', login_view, name='login'),
    path('admin/', admin.site.urls),
    path('sics/', sics_site.urls),
    path('accounts/', include('accounts.urls')),
    path("homepage/", include('scuelo.urls')),

] + static(settings.STATIC_URL)

scuelo/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Q, Max, Sum, Count
from model_utils.models import TimeStampedModel
from django.contrib.auth.models import User

CONDITION_ELEVE = (
    ("CONF", "CONF"),
    ("ABAN", "ABAN"),
    ("PROP", "PROP"),
   ("TBD", "TBD"),
)

HAND = (
    ("DA", "DA"),
    ("DM", "DM"),
    ("DL", "DL"),
    ("DV", "DV"),

)
CS_PY = (
    ("C", "CS"),
    ("E", "EXTRA"),
    ("P", "PY"),
    ("A", "ACC"),
    ("B", "BRAVO"),
)

SEX = (
    ("F", "F"),
    ("M", "M"),
)

TYPE_ECOLE = (
    ("M", "MATERNELLE"),
    ("P", "PRIMAIRE"),
    ("S", "SECONDAIRE"),
    ("L", "LYCEE"),
)


class TypeClasse(TimeStampedModel):
    '''
    2) Then, within the School, the classes are summarized in this order
        a) PS -> MS -> GS
        b) CP1 -> CP2 -> CE1 -> CE2 -> CM1 -> CM2
        c) 6me-> 5me-> 4me-> 3me
        d) 2me -> 1er ->Term
    TIPO DI CLASSE E' QUESTO: DEVE ESSERE ORDINATO IN BASE AL PARAGRAFO 2.5
        • PS, MS, GS), inside the Center
        • 6 years at the Primary School (CP1, CP2, CE1, CE2, CM1, CM2), inside the Centre
        • 4 years at High School (6me, 5me, 4me, 3me), Schools outside the Centre
        • 3 years at High School or Specialization (2me, 1er, Term
    '''
    nom = models.CharField(max_length=100, null=False)
    ordre = models.IntegerField(default=0)
    type_ecole = models.CharField(max_length=1, choices=TYPE_ECOLE, db_index=True)

    def __str__(self):
        return self.nom


class Ecole(TimeStampedModel):
    '''
    1) First, the Schools are ordered in the following order:
        a) our Kindergarten
        b) Our Primary
        c) Other Schools
            i) Kindergarten -> Primary -> Secondary -> High Schools
    '''
    nom = models.CharField(max_length=100, null=False)
    ville = models.CharField(max_length=100, null=False)
    nom_du_referent = models.CharField(max_length=100, null=False)
    prenom_du_referent = models.CharField(max_length=100, null=False)
    email_du_referent = models.CharField(max_length=100, null=False)
    telephone_du_referent = models.CharField(max_length=100, null=False)
#    acronyme = models.CharField(max_length=20, blank=True, null=True)
    note = models.TextField()
#    ordre = models.IntegerField(default=0)
    externe = models.BooleanField(default=True)

    def __str__(self):
        return self.nom


class Classe(TimeStampedModel):
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)
    type = models.ForeignKey(TypeClasse, on_delete=models.CASCADE)
    nom = models.CharField(max_length=10, null=False)
    legacy_id = models.CharField(max_length=100, blank=True, null=True, db_index=True, unique=True)

    '''def __str__(self):
        return '%s %s' % (self.nom, self.get_type_ecole_display())'''

    def __str__(self):
        return '%s %s' % (self.nom, self.type.get_type_ecole_display())


    def get_latest_tariffs(self):
        return self.tarifs.order_by('-version').distinct('causal')
    
    def get_progressive_by_student(self):
        # Sum tariffs (SCO1, SCO2, SCO3) for each student in the class
        return self.tarifs.filter(causal__in=["SCO1", "SCO2", "SCO3"]).aggregate(total=Sum('montant'))['total'] or 0

    def get_progressive_by_class(self):
        # Get the progressive payment based on confirmed PY students
        confirmed_students = Eleve.objects.filter(
            inscription__classe=self,
            condition_eleve="CONF",
            cs_py="P"
        )
        return confirmed_students.count()

    def get_expected_payment(self):
        # Calculate the total amount expected for the class based on confirmed students
        confirmed_students = Eleve.objects.filter(
            inscription__classe=self,
            condition_eleve="CONF",
            cs_py="P"
        )
        total_tarif = self.tarifs.filter(causal__in=["SCO1", "SCO2", "SCO3"]).aggregate(total=Sum('montant'))['total'] or 0
        return confirmed_students.count() * total_tarif
    
    def confirmed_py_count(self):
        # Count the number of PY students who have confirmed their enrollment
        return Eleve.objects.filter(
            inscription__classe=self,
            condition_eleve="CONF",
            cs_py="P"
        ).count()
    
    @property
    def sco_exigible(self):
        total_tarifs = Tarif.objects.filter(classe=self).aggregate(total=Sum('montant'))['total'] or 0
        return total_tarifs
    
class Eleve(TimeStampedModel):
    nom = models.CharField(max_length=34, null=False)
    prenom = models.CharField(max_length=34, null=False)
    date_enquete = models.DateField(null=True, blank=True)  # is  added right after
    condition_eleve = models.CharField(
        max_length=4,
        choices=CONDITION_ELEVE
    )
    sex = models.CharField(max_length=1, choices=SEX)
    date_naissance = models.DateField(blank=True, null=True)
    cs_py = models.CharField(max_length=7, choices=CS_PY, default="C")
    hand = models.CharField(max_length=2, choices=HAND, null=True, blank=True)
    annee_inscr = models.SmallIntegerField(blank=True, null=True)
    parent = models.CharField(max_length=100, blank=True, null=True)
    tel_parent = models.CharField(max_length=100, blank=True, null=True)
    note_eleve = models.TextField(blank=True, null=True, default='-')
    legacy_id = models.CharField(max_length=100, blank=True, null=True, db_index=True, unique=True)

    def __str__(self):
        return f"{self.nom} {self.prenom} ({self.legacy_id})"

    @property
    def an_insc(self):
        return self.annee_inscr.year

    @property
    def current_class(self):
        # Assuming there's a ForeignKey from Inscription to Classe called 'classe'
        current_year = AnneeScolaire.objects.get(actuel=True)
        try:
            # Get the latest inscription for the current year
            inscription = Inscription.objects.filter(eleve=self, annee_scolaire=current_year).latest('date_inscription')
            return inscription.classe
        except Inscription.DoesNotExist:
            return None

    def get_queryset(self, request):
        # Group students by nom_classe
        queryset = Eleve.objects.all().prefetch_related('nom_classe')  # Prefetch for efficiency
        grouped_queryset = {}
        for eleve in queryset:
            classe = eleve.nom_classe.pk  # Get the primary key of nom_classe
            if classe not in grouped_queryset:
                grouped_queryset[classe] = []
            grouped_queryset[classe].append(eleve)
        return grouped_queryset

    def tenu_count(self):
        # Count the number of uniform payments for this student based on the defined conditions
        return self.paiement_set.filter(
            Q(causal='TEN') &
            (
                    Q(montant=4000) | Q(montant=4500) | Q(montant=2250) | Q(montant=2000)
            )
        ).count()

    class Meta:
        verbose_name = 'Eleve'
        verbose_name_plural = 'Eleves'


class AnneeScolaire(TimeStampedModel):
    nom = models.CharField(max_length=100)
    nom_bref = models.CharField(max_length=10, default='')
    date_initiale = models.DateField(blank=True, null=True)  # Allow null here
    date_finale = models.DateField(blank=True, null=True)    # Allow null here
    actuel = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.actuel:
            AnneeScolaire.objects.filter(actuel=True).exclude(pk=self.pk).update(actuel=False)


class Inscription(TimeStampedModel):
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE, blank=True, null=True)
    annee_scolaire = models.ForeignKey(AnneeScolaire, on_delete=models.CASCADE)
    date_inscription = models.DateTimeField(default=timezone.now)  # Add this field
    nombre_uniformes = models.IntegerField(default=0)

    def __str__(self):
        return '%s - %s - %s' % (self.annee_scolaire.nom_bref, self.classe, self.eleve)

    def save(self, *args, **kwargs):
        # Ensure only one inscription for the current year
        if self.annee_scolaire.actuel:
            Inscription.objects.filter(eleve=self.eleve, annee_scolaire__actuel=True).exclude(pk=self.pk).delete()
        super().save(*args, **kwargs)


class Tarif(TimeStampedModel):
    CAUSAL = (
        ("INS", "Inscription"),
        ("SCO1", "Scolarite 1"),
        ("SCO2", "Scolarite 2"),
        ("SCO3", "Scolarite 3"),
        ("TEN", "Tenue"),
        ("CAN", "Cantine"),
    )
    causal = models.CharField(max_length=5, choices=CAUSAL, db_index=True)
    montant = models.PositiveBigIntegerField()
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE,   related_name='tarifs' , blank=True, null=True)
    annee_scolaire = models.ForeignKey(AnneeScolaire, on_delete=models.CASCADE)
    date_expiration = models.DateField("Date d'expiration or tranche dates")
    

    def __str__(self):
        return f"{self.causal} {self.montant} {self.classe}"
    
class Mouvement(TimeStampedModel):
    TYPE = (
        ("R", "Revenus"),
        ("D", "Dépenses"),
    )
    # List possible destinations of the movement
    DESTINATION = (
        ("A", "A"),
        ("B", "B"),
    )
    
    CAUSAL = (
         ("INS", "Inscription"),
        ("SCO1", "Scolarite 1"),
        ("SCO2", "Scolarite 2"),
        ("SCO3", "Scolarite 3"),
        ("TEN", "Tenue"),
        ("CAN", "Cantine"),
    )
    type = models.CharField(max_length=1, choices=TYPE, db_index=True)
    # If D also destination
    #destination = models.CharField(max_length=1, choices=DESTINATION, db_index=True)
    causal = models.CharField(max_length=5, choices=CAUSAL, db_index=True, null=True, blank=True)
    montant = models.PositiveBigIntegerField()
    date_paye = models.DateField(db_index=True, default="")

scuelo/templates/scuelo/tarif/delay_list.html
{% extends "../../layout.html" %}
{% block title %}List of Delays (Late Payments){% endblock %}
{% block content %}
  <h2>Liste générale retards paiements</h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Nom</th>
          <th>Prenom</th>
          <th>Sex</th>
          <th>CS_PY</th>
          <th>SCO</th>
          <th>SCO_exigible</th>
          <th>Diff.</th>
          <th>CAN</th>
          <th>CAN_exigible</th>
          <th>Diff.</th>
          <th>Retards</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
        {% for school, classes in data.items %}
          <tr>
            <td colspan="13"><strong>{{ school }}</strong></td>
          </tr>
          {% for classe, students in classes.items %}
            <tr>
              <td colspan="13">{{ classe }}</td>
            </tr>
            {% for student in students %}
              <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.nom }}</td>
                <td>{{ student.prenom }}</td>
                <td>{{ student.sex }}</td>
                <td>{{ student.cs_py }}</td>
                <td>{{ student.sco }}</td>
                <td>{{ student.sco_exigible }}</td>
                <td>{{ student.diff_sco }}</td>
                <td>{{ student.can }}</td>
                <td>{{ student.can_exigible }}</td>
                <td>{{ student.diff_can }}</td>
                <td>{{ student.retards }}</td>
                <td>{{ student.note }}</td>
              </tr>
            {% endfor %}
          {% endfor %}
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

scuelo/templates/scuelo/tarif/tarif_confirm_delete.html
{% extends "../../layout.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Delete Tarif</h2>
    <p>Are you sure you want to delete this tarif?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <button type="submit" name="cancel" class="btn btn-secondary">Cancel</button>
    </form>
</div>
{% endblock %}

scuelo/templates/scuelo/tarif/tarif_form.html
{% extends "../../layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    .form-container {
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        max-width: 800px;
        margin: 0 auto;
    }

    h3 {
        text-align: center;
        color: #000;
        font-weight: bold;
        margin-bottom: 20px;
        font-size: 1.5rem;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .btn-submit {
        background-color: #007bff;
        color: white;
        padding: 10px;
        font-size: 14px;
        width: 100%;
        text-align: center;
        border-radius: 5px;
        border: none;
        margin-top: 10px;
    }

    .btn-submit:hover {
        background-color: #0056b3;
    }

    .btn-back {
        background-color: #6c757d;
        color: white;
        padding: 10px;
        font-size: 14px;
        text-align: center;
        border-radius: 5px;
        border: none;
        margin-top: 10px;
        display: inline-block;
    }

    .btn-back:hover {
        background-color: #5a6268;
    }

    .form-footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 20px;
    }
</style>

<div class="form-container">
    <h3>{% if form.instance.pk %}Modifier Tarif{% else %}Ajouter Tarif{% endif %}</h3>
    
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <div class="form-footer">
            <button type="submit" class="btn-submit">
                {% if form.instance.pk %}Enregistrer les modifications{% else %}Ajouter Tarif{% endif %}
            </button>

            <a href="{% url 'manage_tarifs' classe.pk %}" class="btn-back">Annuler</a>
        </div>
    </form>
</div>
{% endblock content %}

scuelo/templates/scuelo/tarif/tarif_list.html
{% extends "../../layout.html" %}

<style>
    .table-container {
        max-width: 100%;
        overflow-x: auto;
        border-radius: 10px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .table th, .table td {
        padding: 12px;
        text-align: center;
        border: 1px solid #dee2e6;
        background-color: #f9f9f9;
        transition: background-color 0.3s;
    }

    .table th {
        background-color: #007bff;
        color: #fff;
        text-transform: uppercase;
        font-weight: bold;
    }

    .btn-primary {
        background-color: #007bff;
        border: none;
        border-radius: 20px;
        padding: 10px 20px;
        transition: background-color 0.3s;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        transform: translateY(-2px);
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }

    .table tbody tr:hover {
        background-color: #e9ecef;
    }
</style>

{% block content %}
    <a href="{% url 'add_tarif' classe.pk %}" class="btn btn-primary mb-3">
        <i class="fas fa-money-check-alt"></i> Ajouter un Tarif
    </a>

    <div class="table-responsive table-container">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Causal</th>
                    <th>Montant (FCFA)</th>
                    <th>Date d'expiration</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for tarif in tarifs %}
                <tr>
                    <td>{{ tarif.get_causal_display }}</td>
                    <td>{{ tarif.montant }}</td>
                    <td>{{ tarif.date_expiration }}</td>
                    <td>
                        <a href="{% url 'update_tarif' tarif.pk %}" class="btn btn-warning btn-sm">
                            <i class="fas fa-pencil-alt"></i> Modifier
                        </a>
                        <a href="{% url 'delete_tarif' tarif.pk %}" class="btn btn-danger btn-sm">
                            <i class="fas fa-trash-alt"></i> Supprimer
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Aucun tarif disponible pour cette classe.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <h4>Étudiant Details</h4>
<ul>
    <li>Total Étudiants: {{ student_count }}</li>
    <li>Étudiants PY Confirmés: {{ confirmed_py_count }}</li>
    <li>Étudiants CS: {{ cs_students_count }}</li> <!-- Updated CS students count -->
    <li>Étudiants PY: {{ py_students_count }}</li>
    <li>Autres Étudiants: {{ other_students_count }}</li>
</ul>
    <h4>Progressive Payments</h4>
    <ul>
        <li>Total par élève: {{ progress_per_eleve }} FCFA</li>
        
        <li>Étudiants PY Confirmés: {{ confirmed_py_count }}</li>
        <li>Étudiants CS: {{ cs_students_count }}</li>
        <li>Étudiants PY: {{ py_students_count }}</li>
        <li>Autres Étudiants: {{ other_students_count }}</li>
    </ul>
    
    <h4>Tranche Details</h4>
    <ul>
        <li>Paiement attendu (1ère tranche): {{ tranche_data.first_tranche }} FCFA</li>
    <li>Paiement attendu (2ème tranche): {{ tranche_data.second_tranche }} FCFA</li>
    <li>Paiement attendu (3ème tranche): {{ tranche_data.third_tranche }} FCFA</li>
        <li>Total reçu: {{ total_actual_payments }} FCFA</li>
    </ul>
    
{% endblock %}